### PR TITLE
fix/name_initials

### PR DESCRIPTION
**Pull request by bcdiaconu**
@krisjans my android studio must not be setup properly because it does not help in any way with auto complete and static code check. therefore there must be quite a few errors. maybe you could help me with setting up as I always struggled with devops/envs.

### CODE REVIEW

**Comment by bcdiaconu** [comment]
I finally managed to make the env work. I will debug and push

**Comment by krisjans** [comment]
Hi @bcdiaconu !
I think you need to enable/setup `Java CI with Gradle` workflow in your fork's [`Actions`](https://github.com/bcdiaconu/openScale/actions). Build configuration script is already committed into builder branch - see file https://github.com/bcdiaconu/openScale/blob/builder/.github/workflows/gradle.yml

**Comment by bcdiaconu** [comment]
Now we are talking business.👍  I will close this PR and reopen when feeling fine with it. 

Can we also do something like testing with this CI before giving a checkmark?

**Comment by krisjans** [comment]
> Can we also do something like testing with this CI before giving a checkmark?

As far as I understand - this green check-mark is result of automatic build/workflow.
I don't know if it is possible to add some "manual-testing" workflow in github.

**Comment by bcdiaconu** [comment]
It must certainly is possible to add automated testing. Generally they would be integration tests. However this project don't seem to have any. So the checkmark is for both build and tests, if testing is added to pipeline.

But the CI could test unit tests. That is because if unit tests are not run locally by a developer, if something is broken in the covered code, it will be marked as fail and hopefully will not create the debug binaries. And of course developer would know he has done something wrong.

**Comment by krisjans** [comment]
I think unit tests are executed during build and build fails if you break any tests. But... let me check that...

**Comment by krisjans** [comment]
OK, I was wrong! Unit-tests are not enabled by default.  You need to enable unit-tests in workflow config file. Here I updated my builder branch: https://github.com/krisjans/openScale/commit/dfa38d77aa6c9df71d1f5b84dbbccb3776f8f4a8

p.s. When you update your builder branch it will trigger a build and will create `debug_latest` pre-realease from builder branch. To get normal build back you must commit something into your work branch to trigger another build.

**Pull request closed without merging**
